# Generated by Django 4.2.4 on 2023-08-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('number', models.IntegerField(verbose_name='Number')),
            ],
            options={
                'verbose_name': 'Test model',
                'verbose_name_plural': 'Test models',
            },
        ),
    ]
